apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadtest-host
  labels:
    app: loadtest-host
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadtest-host
  template:
    metadata:
      labels:
        app: loadtest-host
    spec:
      containers:
      - name: loadtest-host
        image: kagenopriest/loadtest-host:1.4.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      # Force Host to run on Master/Control Plane if possible, or just standard scheduling
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: loadtest-host-service
spec:
  type: NodePort
  selector:
    app: loadtest-host
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30001
